name: CMS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Adjust according to your Laravel PHP version

      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up SSH agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -p 65002 ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.USER }}@${{ secrets.HOST }} "echo 'SSH Connection Successful'"

      # Sync files to the server
      - name: Sync files to server
        run: |
          rsync -e "ssh -p 65002" -avz --delete --no-times \
          --exclude '.env' \
          --exclude '.git' \
          --exclude '.gitignore' \
          --exclude 'node_modules' \
          --exclude 'vendor' \
          --exclude 'bootstrap/cache' \
          --exclude 'public' \
          --exclude 'storage' \
          --exclude 'storage/debugbar' \
          --exclude 'tests' \
          --exclude 'docker' \
          --exclude '.DS_Store' \
          . ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/domains/mau-portfolio-cms.mallshuck.io/public_html

      # Install dependencies and clear cache
      - name: Clear Laravel cache and install dependencies
        run: |
          ssh -p 65002 ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd /home/${{ secrets.USER }}/domains/mau-portfolio-cms.mallshuck.io/public_html
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          EOF

      # Build frontend assets
      - name: Run npm build production
        run: |
          ssh -p 65002 ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd /home/${{ secrets.USER }}/domains/mau-portfolio-cms.mallshuck.io/public_html
          npm ci
          npm run build
          EOF
